import os
import datetime
import conf

# --- ユーザーが設定する項目 ---
hdphc_dir = f"{conf.param_dir}/HDPHC"
OUTPUT_FILE = f"{hdphc_dir}/HodoPHCParam_1"

DETECTOR_CONFIG = {
     1: 63, # CId 1 BHT
     3: 15, # CId 3 BH2
     5: 34, # CId 5 HTOF
     7:  1, # CId 7 T1
     8:  8, # CId 8 CVC
     11: 8  # CId 11 COBO
}

DETECTOR_NAME = {
     1: "BHT", # CId 1 BHT
     3: "BH2", # CId 3 BH2
     5: "HTOF", # CId 5 HTOF
     7: "T1", # CId 7 T1
     8: "CVC", # CId 8 CVC
     11: "COBO"  # CId 11 COBO
}

# PlIdのリスト (今回は [0] で固定)
PLID_LIST = [0]

# ★ CIdごとに UorD のリストを定義します。
UORD_LIST_BY_CID = {
    "default": [0, 1],
     7 : [0],
    11 : [0]
}

# Type と nParam の固定値
DEFAULT_NPARAM = 3

def get_initial_params_phc(CId, PlId, SegId, UorD):
    """
    PHCパラメータ (p0, p1, p2) の初期値を返す関数。
    ここをカスタマイズしてください。
    """
    
    # サンプルファイル [cite: 1] では CId=1, 2 以外は 0.0 のため、
    # これをデフォルト値とします。
    p0 = 0.0
    p1 = 0.0
    p2 = 0.0
    phc_type = 1

    # --- CId ごとに初期値を設定 ---
    if CId == 7:
        phc_type = 0
    elif CId == 11:
        phc_type = 0
            
    # p0, p1, p2 をタプルで返す
    return phc_type, p0, p1, p2

# --- スクリプト本体 ---

def format_line_phc(CId, PlId, SegId, UorD, Type, nParam, p0, p1, p2):
    """
    ファイルに書き込む行をフォーマットする。
    区切り文字はタブ文字 (\t) を使用します。
    """
    # {p0:e} は指数表記 (例: 1.2345e+01)
    # {p0:f} は固定小数点表記 (例: 12.345000)
    # サンプルファイル [cite: 1] は指数表記と固定小数点が混在していますが、
    # ここでは指数表記で統一します (値が0でも 0.00000e+00 となります)
    return (
        f"{CId}\t{PlId}\t{SegId}\t{UorD}\t{Type}\t{nParam}\t"
        f"{p0:e}\t{p1:e}\t{p2:e}"
    )


def main():
    print(f"PHCパラメータファイル {OUTPUT_FILE} を生成します...")
    
    try:
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            # 1. ヘッダーを書き込む
            timestamp = datetime.datetime.now().isoformat(sep=' ', timespec='microseconds')
            # f.write(f"# {timestamp} generated by this python script\n")
            f.write("#CId\tPlId\tSegId\tUorD\tType\tnParam\tp0\tp1\tp2\n")
            
            # 2. 設定に基づいてループ処理
            # CIdでループ
            for CId, seg_count in DETECTOR_CONFIG.items():
                f.write(f"# {DETECTOR_NAME[CId]}\n")
                # PlIdでループ
                for PlId in PLID_LIST:
                    
                    # UorD の組み合わせリストを取得
                    uord_list = UORD_LIST_BY_CID.get(CId, UORD_LIST_BY_CID["default"])
                    
                    # UorD でループ
                    for UorD in uord_list:
                    
                        # SegIdでループ
                        for SegId in range(seg_count):
                            
                            # 3. 初期値を取得
                            phc_type, p0, p1, p2 = get_initial_params_phc(CId, PlId, SegId, UorD)
                            
                            # 4. 行をフォーマット
                            line = format_line_phc(
                                CId, PlId, SegId, UorD, 
                                phc_type, DEFAULT_NPARAM, 
                                p0, p1, p2
                            )
                            
                            # 5. ファイルに書き込み
                            f.write(line + "\n")
                                
        print(f"ファイル {OUTPUT_FILE} の生成が完了しました。")
        print(f"パス: {os.path.abspath(OUTPUT_FILE)}")

    except IOError as e:
        print(f"ファイルの書き込み中にエラーが発生しました: {e}")
    except Exception as e:
        print(f"予期せぬエラーが発生しました: {e}")

# スクリプトとして実行された場合のみmain()を呼び出す
if __name__ == "__main__":
    main()